title: Pham Ngoc Quang
author: Pham Ngoc Quang
description: Portfolio of Pham Ngoc Quang, Backend Developer Intern
remote_theme: daattali/beautiful-jekyll

plugins:
  - jekyll-remote-theme

social-network-links:
  linkedin: https://www.linkedin.com/in/qnp211004/
  github: https://github.com/quangpham10212004

navbar-links:
  About Me: "about"
  Projects: "projects"

avatar: # Add path to avatar image if you have one, e.g., /assets/img/avatar.jpg

footer-links:
  email: qpquangpham10212004@gmail.com

projects:
  - name: ITRMS
    description: Internal Task & Resource Management System
    link: https://github.com/quangpham10212004/ITRMS
  - name: bookstore_microservice
    description: Book Store Web Using Django As Backend and Microservices Architecture
    link: https://github.com/quangpham10212004/bookstore_microservice
  - name: Laptop_Store_App
    description: Laptop Store App Using Jetpack Compose
    link: https://github.com/quangpham10212004/Laptop_Store_App
  - name: config-nvim
    description: Config For My Neovim
    link: https://github.com/quangpham10212004/config-nvim
